on: [push, pull_request]

jobs:
  push-to-myget:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
        
      - name: setup nuget.exe
        uses: nuget/setup-nuget@v1
      
      - name: build and push
        shell: pwsh
        run: |
          cd build
          .\build2.ps1
          nuget pack build.nuspec -version 3.4.0-beta.${env:GITHUB_RUN_NUMBER}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: version-3.40
          path: build/*.nupkg
